define([], function () {


    var Events = {};

    /**
     * Given an event generated by clicking <a href='#something'> return a jquery element referencing the link a string
     * wit the href content, minus the #.
     *
     * @returns {{link: (*|jQuery|HTMLElement), actionName: (XML|string|void)}}
     */
    Events.eventDetail = function (event) {
        event.preventDefault();
        var link = $(event.target),
            target = link.attr('href'),
            actionName = target.replace('#', '');
        return { link: link, actionName: actionName};
    };

    return Events;

});