var redshiftsoft = {};

redshiftsoft.Assert = {};

/**
 * Throws an error if the specified object is not an Integer.
 */
redshiftsoft.Assert.isInteger = function (testArg, message) {
    if (!((typeof testArg === "number") && (Math.floor(testArg) === testArg))) {
        throw new Error(message);
    }
};

/**
 * Given an event generated by clicking <a href='#something'> return a jquery element referencing the link a string
 * wit the href content, minus the #.
 *
 * @returns {{link: (*|jQuery|HTMLElement), actionName: (XML|string|void)}}
 */
redshiftsoft.eventDetail = function (event) {
    event.preventDefault();
    var link = $(event.target),
        target = link.attr('href'),
        actionName = target.replace('#', '');
    return { link: link, actionName: actionName};
};